name: Deploy Storybook

on:
  push:
    branches:
      - 'main'

jobs:
  storybook-gh-pg:
    name: Deploy Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm ci

      - name: Deploy Storybook to gh-page
        env:
          GH_TOKEN: ${{ github.actor }}:${{secrets.GITHUB_TOKEN}}
        run: npm run deploy-storybook -- --ci
